all: src/uaf.c src/note.c src/t-note.c src/election.c src/note++.c
	gcc src/uaf.c -o ./uaf/share/uaf
	gcc src/note.c -o ./note/share/note
	gcc src/t-note.c -o ./t-note/share/t-note
	gcc src/election.c -o ./election/share/election
	gcc src/note++.c -o ./note++/share/note++

clean:
	rm uaf/share/uaf note/share/note t-note/share/t-note election/share/election note++/share/note++